import { pageHeading,button,table } from '../components/ui.js';
import { escapeHtml as h,number } from '../utils.js';
import { capacityConfigurations,capacityPeriodLabel } from '../capacity/capacityService.js';
export function render(data){
  const capacities=capacityConfigurations(data.capacityRules),month=value=>`${String(value.month).padStart(2,'0')}/${value.year}`;
  return `${pageHeading('Suas fazendas e seus dados','Gerencie o controle e mantenha uma cópia dos registros.',button('Nova fazenda','new-farm'))}
  ${data.farm&&!data.readOnly?`<section class="panel"><h3>${h(data.farm.name)}</h3><p>Controle: ${data.farm.controlMode==='pasture'?'por pastos':'fazenda inteira'} · Capacidade ${data.farm.capacityEnabled?'ativada':'desativada'}</p><div class="row-actions">${button('Editar fazenda','farm-settings')}${button('Mudar modo de controle','change-mode')}${button('Cadastrar proprietário','new-owner')}${button('Definir capacidade mensal','capacity-form')}</div></section><section class="panel"><h3>Capacidades configuradas</h3>${table(['Início','Período','Fim','Local','Cabeças','Avisar em','Situação','Ações'],capacities.map(r=>[month(r),capacityPeriodLabel(r.months),month(r.end),h(r.pastureId?data.pastures.find(p=>p.id===r.pastureId)?.name||'Pasto':'Fazenda inteira'),number(r.maxHeads),`${r.warningPercentage}%`,r.active?'Ativa':'Desativada',`<div class="row-actions">${button('Editar','edit-capacity',r.id,'text-button')}${button('Excluir','delete-capacity',r.id,'text-button red')}</div>`]))}</section>`:'<p class="notice">Selecione uma fazenda para editar seu modo e sua capacidade.</p>'}
  <section class="panel"><h3>Backup e restauração</h3><p>O backup acompanha o contexto selecionado e inclui fotos. A restauração cria fazendas separadas e mantém os dados atuais.</p><div class="row-actions">${button('Exportar backup','export-backup')}${button('Importar backup','import-backup')}</div></section>
  <section class="panel"><h3>Dados da versão local</h3><p>Migre os dados deste navegador para uma fazenda vazia. A cópia local será mantida.</p><div class="row-actions">${button('Ver dados locais para migração','migrate-local')}${button('Exportar backup local','export-legacy')}</div></section>
  <section class="panel"><h3>Uso no campo</h3><p>Abra a fazenda com internet antes de sair. Sem conexão, use + e − para registrar movimentações e fotos. Acompanhe a fila em Alertas.</p><p>Ao sair da conta, as pendências ficam protegidas pelo contexto desta conta neste navegador. Entre novamente na mesma conta para sincronizar.</p>${button('Sair da conta','logout')}</section>`;
}
